yogue/algoritmos/urls.py
from django.urls.resolvers import URLPattern
from . import views
from django.urls import path

app_name='algoritmos'

urlpatterns=[
    path('',views.index,name='index'),
    path('apriori',views.apriori,name='apriori'),
    path('distancias',views.distancias,name='distancias'),
    path('clustering-jerarquico',views.cluster_jerarquico,name='cluster_jerarquico'),
    path('clustering-particional',views.cluster_particional,name='cluster_particional'),
    path('clasificacion-regresion-logistica',views.clasif_rlog,name='clasif_rlog'),
    path('arboles-de-pronostico',views.a_pronostico,name='a_pronostico'),
    path('arboles-de-clasificacion',views.a_clasif,name='a_clasif'),
    path('upload-files',views.upload,name='upload'),
    path('prediccion',views.prediccion,name='prediccion'),
]

yogue/yogue/urls.py
from django.contrib import admin
from django.urls import path
from algoritmos import views
# Use include() to add paths from the project application 
#from django.urls import include

# used to Add URL maps to redirect the base URL to our application

#from django.views.generic import RedirectView

# Used to use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('algoritmos.urls', namespace='algoritmos')),
] 
# solo para fines de depuracion:
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yogue/algoritmos/models.py
from django.db import models

# Create your models here.

class Document(models.Model):
    document = models.FileField(upload_to='data/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

yogue/algoritmos/forms.py
from django import forms
from .models import Document

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ( 'document', )

yogue/algoritmos/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import DocumentForm
from .models import Document
from .scripts import file
from .scripts import apriori_mod
from .scripts import metric_mod
from .scripts import clst_jrq_mod
from .scripts import clst_part_mod
from .scripts import clasif_rlog_mod
from .scripts import arbol_pronostico_mod
from .scripts import arbol_clasificacion_mod
import os
from random import sample

# Create your views here.
def index(request):
    return render(request,"index.html")

def upload(request):
    if request.method == 'POST':
        
        if request.FILES.get('document') :
            form = DocumentForm(request.POST, request.FILES)
            if form.is_valid():
                all_docs=Document.objects.all()
                for doc in all_docs:
                    try:
                        os.remove(doc.document.path)
                    except:
                        continue
                Document.objects.all().delete()
                form.save()
                all_docs = Document.objects.all()
                request.session['file_name']=all_docs[0].document.path

                return render(request, 'upload.html', {
                            'fileStatus': 'success',
                            'file_uploaded':os.path.basename(request.session['file_name']),
                            'data':file.get_data(request.session['file_name'])
                        })
            else:
                return render(request, 'upload.html', {
                    'fileStatus': 'fail',
                    'form': True
                })    
        elif request.POST.get('delete') :
            all_docs=Document.objects.all()
            for doc in all_docs:
                try:
                    os.remove(doc.document.path)
                except:
                    continue
            Document.objects.all().delete()
            del request.session['file_name']
            file_uploaded=False
            return render(request, 'upload.html',{
                'form': True,
                'file_uploaded':file_uploaded
            })
    else:
        file_uploaded= os.path.basename(request.session['file_name']) if 'file_name' in request.session.keys() else False
        data_param= file.get_data(request.session['file_name']) if request.session.get('file_name') else False
        return render(request, 'upload.html',{
                'form': True,
                'file_uploaded':file_uploaded,
                'data': data_param
            })

def apriori(request):
    if 'file_name' in request.session.keys():
        if request.method == 'POST':
            if request.POST.get('min_support') and request.POST.get('min_confidence') and request.POST.get('min_lift'):
                min_sup=float(request.POST['min_support'])
                min_conf=float(request.POST['min_confidence'])
                min_lif=float(request.POST['min_lift'])
                lista_rules=apriori_mod.get_rules(request.session['file_name'],min_sup,min_conf,min_lif)
            else:
                lista_rules=False
        else:
            lista_rules=False
        return render(request,"apriori.html",{
            'file_name':os.path.basename(request.session['file_name']),
            'data': sample(file.get_data(request.session['file_name']), 100),
            'frecuency_table': apriori_mod.frecuencia(request.session['file_name']),
            'image_frecuency_url': apriori_mod.bar_frecuency(request.session['file_name']),
            'lista_rules': lista_rules
        })


    else:
        print("file not uploaded")
        return render(request,"apriori.html")

def distancias(request):
    if 'file_name' in request.session.keys():
        if request.method == 'POST':
            if request.POST.get('metric'):
                metrica=request.POST['metric']
                matriz=metric_mod.get_matriz(request.session['file_name'],metrica)
                request.session['metrica']=metrica
                distancia2=False
                vector1=False
                vector2=False
            elif request.POST.get('vector1') and request.POST.get('vector2'):
                vector1=int(request.POST['vector1'])
                vector2=int(request.POST['vector2'])
                distancia2= metric_mod.get_single_distance(request.session['file_name'],vector1,vector2,request.session['metrica'])
                metrica=request.session['metrica']
                matriz=metric_mod.get_matriz(request.session['file_name'],metrica)
            else:
                vector1=False
                vector2=False
                distancia2=False
                metrica=False
                matriz=False
        else:
            vector1=False
            vector2=False
            distancia2=False
            metrica=False
            matriz=False
        return render(request,"metricas_distancias.html",{
            'file_name':os.path.basename(request.session['file_name']),
            'data': file.get_data(request.session['file_name'])[0:20],
            'dst_matrix': matriz,
            'metrica': metrica,
            'single_distance': distancia2,
            'vector1': vector1,
            'vector2': vector2
        })    
    else:
        return render(request,"metricas_distancias.html")    
    
def cluster_jerarquico(request):
    if 'file_name' in request.session.keys():
        if request.POST:
            if request.POST.get('predictoras'):
                request.session['column_list']=request.POST.getlist('predictoras')
                dendograma_url = clst_jrq_mod.get_dendograma_url(request.session['file_name'],request.session['column_list'])
                M_corr=file.get_matriz_corr(request.session['file_name'])
                return render(request,"cluster_jerarquico.html",{
                    'file_name':os.path.basename(request.session['file_name']),
                    'data': file.get_data(request.session['file_name'])[0:20],
                    'Matriz_corr': M_corr,
                    'heatmap_url': file.get_heatmap(request.session['file_name']),
                    'variables': M_corr[0][1::],
                    'dendograma_url':dendograma_url
                })
            elif request.POST.get('numClusters'):
                numClusters=request.POST['numClusters']
                dataEtq,list_clusters=clst_jrq_mod.get_cluster_data(request.session['file_name'],request.session['column_list'],int(numClusters))

                dendograma_url = clst_jrq_mod.get_dendograma_url(request.session['file_name'],request.session['column_list'])
                M_corr=file.get_matriz_corr(request.session['file_name'])
                return render(request,"cluster_jerarquico.html",{
                    'file_name':os.path.basename(request.session['file_name']),
                    'data': file.get_data(request.session['file_name'])[0:20],
                    'Matriz_corr': M_corr,
                    'heatmap_url': file.get_heatmap(request.session['file_name']),
                    'variables': M_corr[0][1::], #columnas posibles
                    'dendograma_url':dendograma_url,
                    'list_clusters': list_clusters,
                    'dataCluster': dataEtq
                })
            else:
                M_corr=file.get_matriz_corr(request.session['file_name'])
                return render(request,"cluster_jerarquico.html",{
                    'file_name':os.path.basename(request.session['file_name']),
                    'data': file.get_data(request.session['file_name'])[0:20],
                    'Matriz_corr': M_corr,
                    'heatmap_url': file.get_heatmap(request.session['file_name']),
                    'variables': M_corr[0][1::]
                })
        else:
            M_corr=file.get_matriz_corr(request.session['file_name'])
            return render(request,"cluster_jerarquico.html",{
                'file_name':os.path.basename(request.session['file_name']),
                'data': file.get_data(request.session['file_name'])[0:20],
                'Matriz_corr': M_corr,
                'heatmap_url': file.get_heatmap(request.session['file_name']),
                'variables': M_corr[0][1::]
            })
    else:
        return render(request,"cluster_jerarquico.html")

def cluster_particional(request):
    if 'file_name' in request.session.keys():
        if request.POST:
            if request.POST.get('predictoras'):
                request.session['column_list']=request.POST.getlist('predictoras')
                best_n = clst_part_mod.get_best_n_cluster(request.session['file_name'],request.session['column_list'])
                M_corr=file.get_matriz_corr(request.session['file_name'])
                return render(request,"cluster_particional.html",{
                    'file_name':os.path.basename(request.session['file_name']),
                    'data': file.get_data(request.session['file_name'])[0:20],
                    'Matriz_corr': M_corr,
                    'heatmap_url': file.get_heatmap(request.session['file_name']),
                    'variables': M_corr[0][1::],
                    'best_n': best_n
                })
            elif request.POST.get('numClusters'):
                numClusters=request.POST['numClusters']
                dataEtq,list_clusters=clst_part_mod.get_cluster_data(request.session['file_name'],request.session['column_list'],int(numClusters))

                best_n = clst_part_mod.get_best_n_cluster(request.session['file_name'],request.session['column_list'])
                M_corr=file.get_matriz_corr(request.session['file_name'])
                return render(request,"cluster_particional.html",{
                    'file_name':os.path.basename(request.session['file_name']),
                    'data': file.get_data(request.session['file_name'])[0:20],
                    'Matriz_corr': M_corr,

yogue/algoritmos/templates/401.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>404 Error - SB Admin</title>
        <link href="css/styles.css" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <div id="layoutError">
            <div id="layoutError_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-6">
                                <div class="text-center mt-4">
                                    <h1 class="display-1">401</h1>
                                    <p class="lead">Unauthorized</p>
                                    <p>Access to this resource is denied.</p>
                                    <a href="index.html">
                                        <i class="fas fa-arrow-left me-1"></i>
                                        Return to Dashboard
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutError_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2021</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
    </body>
</html>

yogue/algoritmos/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Yogue</title>
        <link rel="icon" href="{% static 'assets/img/favicon.ico' %}" type="image/x-icon">
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'css/style-checkbox.css' %}" rel="stylesheet" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
       
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        {% block head-content %} {% endblock %}


    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="{% url 'algoritmos:index' %}">
                <img src="{% static 'assets/img/favicon-32x32.png' %}" alt="" width="24" height="24">
                Yogue
            </a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Data</div>
                            <a class="nav-link" href="{% url 'algoritmos:upload' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-file-upload"></i></div>
                                Subir archivos
                            </a>
                            <div class="sb-sidenav-menu-heading">Algoritmos</div>
                            <a class="nav-link" href="{% url 'algoritmos:apriori' %}">
                                <div class="sb-nav-link-icon"><i class="far fa-object-group"></i></div>
                                Algoritmo Apriori
                            </a>
                            <a class="nav-link" href="{% url 'algoritmos:distancias' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Metricas de distancia
                            </a>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-th-large"></i></div>
                                Clustering
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="{% url 'algoritmos:cluster_jerarquico' %}">Jerárquico(Ascendente)</a>
                                    <a class="nav-link" href="{% url 'algoritmos:cluster_particional' %}">Particional (K-means)</a>
                                </nav>
                            </div>
                            <a class="nav-link" href="{% url 'algoritmos:clasif_rlog' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-line"></i></div>
                                Clasificacion con R. Logistica
                            </a>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseArboles" aria-expanded="false" aria-controls="collapseArboles">
                                <div class="sb-nav-link-icon"><i class="fas fa-tree"></i></div>
                                Arboles de decisión
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseArboles" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="{% url 'algoritmos:a_pronostico' %}">Pronóstico</a>
                                    <a class="nav-link" href="{% url 'algoritmos:a_clasif' %}">Clasificación</a>
                                </nav>
                            </div>
                            <div class="sb-sidenav-menu-heading">Usuario Final</div>
                            <a class="nav-link" href="{% url 'algoritmos:prediccion' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Predicciones
                            </a>
                          
                        </div>
                    </div>

                </nav>
            </div>
            <div id="layoutSidenav_content">
                
                {% block content %}<!--- CONTENIDO DE CADA PÁGINA --> {% endblock %}



                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Yogue 2021</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
        <script src="{% static 'js/mdboostrap_code.js' %}"></script>

    </body>
</html>

yogue/algoritmos/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
                <main>
                    <div class="">
                        <header class="masthead d-flex align-items-center">
                            <div class="container px-4 px-lg-5 text-center">
                                <h1 class="mb-1">Yogue</h1>
                                <h3 class="mb-5"><em>La cooperación perfecta entre IA y humanos</em></h3>
                                <a class="btn btn-primary btn-xl" href="{% url 'algoritmos:upload' %}">Empieza ahora</a>
                            </div>
                        </header>
                    </div>
                </main>
{% endblock %}

yogue/algoritmos/templates/prediccion.html
{% extends "base.html" %}

{% block content %}
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">Predicción{% if algoritmo %} con {{algoritmo}} {% endif %}
                        </h1>
                        {% if vars %}
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">Ingrese los datos para predecir</li>
                        </ol>
                        <hr>
                        <form method="post" class="mb-5" enctype="multipart/form-data">{% csrf_token %}
                            <div class="container">
                                <div class="row mx-5">
                                    {% for var in vars %}
                                    <div class="col-md-4 my-2">
                                      <div class="form-floating">
                                        <input type="number" name="{{var}}" class="form-control" id="floatingInput_{{var}}" placeholder="{{var}}" value="" step="0.000001" required>
                                        <label for="floatingInput_{{var}}">{{var}}</label>
                                      </div>
                                    </div>
                                    {% endfor %}
                                    <div class="w-25 mx-auto">
                                        <button type="submit" class="form-control btn btn-primary mb-3">Obtener Prediccion</button>
                                    </div>
                                </div>
                            </div>    
                        </form>
                        {% endif %}
                        {% if result %}
                        <div class="alert alert-info" role="alert">
                            El resultado es: <strong>{{result}}</strong>
                        </div>
                        {% endif %}
                    </div>
                </main>
{% endblock %}

yogue/algoritmos/templates/upload.html
{% extends "base.html" %}
{% load static %}

{% block content %}
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">Subir información</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">Favor de subir un archivo csv con datos</li>
                        </ol>
                        <!-- formulario -->
                        {% if not file_uploaded %}
                            <h3 class="display-6">Subir datos para analizar</h1>
                        {% else %}
                            <h3 class="display-6">Ya se ha subido el archivo: {{ file_uploaded }}</h1>
                        {% endif %}
                        <form method="post" enctype="multipart/form-data">{% csrf_token %}
                            <div class="row">
                                {% if fileStatus and fileStatus == "success"  %}
                                    <div class="alert alert-success" role="alert">
                                        Subido existosamente
                                    </div>
                                {% else %}
                                    <div class="col mb-3">
                                        {% if form %}
                                         <div class="mb-3">
                                            {% if not file_uploaded %}
                                                <input class="form-control" type="file" id="id_document" accept=".csv" name="document" required>
                                            {% else %}
                                                <input class="form-control" type="file" id="id_document" accept=".csv" name="document" disabled>
                                            {% endif %}
                                          </div>
                                        {% endif %}
                                    </div>
                                    <div class="col-2 mb-3">
                                        {% if not file_uploaded %}
                                            <button type="submit" class="form-control btn btn-primary">Subir archivo</button>
                                        {% else %}
                                            <button type="submit" class="form-control btn btn-primary" disabled>Subir archivo</button>
                                        {% endif %}
                                    </div>    
                                {% endif %}                                
                            </div>
                            {% if fileStatus and fileStatus == "fail" %}
                            <div class="row">
                                <div class="alert alert-danger" role="alert">
                                    Ocurrió un error, por favor trata de subirlo nuevamente
                                 </div>     
                            </div>
                            {% endif %}
                        </form>
                        {% if file_uploaded or fileStatus == "success"  %}
                            <form method="post" enctype="multipart/form-data">{% csrf_token %}
                                <div class="d-none">
                                    <input class="form-check-input" type="radio" name="delete" checked>
                                </div>
                                <div class="w-50 mx-auto">
                                    <button type="submit" class="form-control btn btn-warning mb-3">Subir otro archivo</button>
                                </div>
                                
                            </form>
                        {% endif %}
                        {% if file_uploaded and data  %}
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                                {{file_uploaded}}
                            </div>
                            <div class="card-body">
                                <table id="datatablesSimple">
                                    {% for row in data %}
                                        {% if forloop.first %} <!-- header de la tabla-->
                                            <thead>
                                                <tr>
                                            {% for col in row %}
                                                    <th>{{ col }}</th>
                                            {% endfor %}    
                                                </tr>
                                            </thead>
                                            <tfoot>
                                                <tr>
                                            {% for col in row %}
                                                    <th>{{ col }}</th>
                                            {% endfor %}    
                                                </tr>
                                            </tfoot>
                                        {% elif forloop.counter == 2  %} <!-- poner tbody-->
                                            <tbody>
                                                <tr>
                                            {% for col in row %}
                                                    <td>{{ col }}</td>        
                                            {% endfor %}
                                                </tr>
                                        {% else %} <!-- informacion extra -->
                                                <tr>
                                            {% for col in row %}
                                                    <td>{{ col }}</td>        
                                            {% endfor %}
                                                </tr>
                                        {% endif %}
                                            
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </main>
{% endblock %}